### ISSUE TITLE
Custom card component error

### ISSUE THREAD

**Issue by gerliczky** [azuwis/zigbee2mqtt-networkmap#10]
**Describe the bug**
The custom card component does not show up on the screen. The sensor entity state is unknown. 
There is only one line in the log about the subscription of the mqtt topic: "Subscribing to zigbee2mqtt/bridge/networkmap/raw " But there is no more message on the log in this topic.

sensor config:
```
sensor:
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
```

Lovelace UI config:
 ```
 cards:
    - type: custom:zigbee2mqtt-networkmap
      entity: sensor.zigbee2mqtt_networkmap

  resources:
    - url: /local/zigbee2mqtt-networkmap.js?v=0.5.0retry
      type: module
```
The 0.5.0 released version of the zigbee2mqtt-networkmap.js is copied to the  www folder.

The following error appear on the lovelace UI.

**Screenshots**
Entity state:
![image](https://user-images.githubusercontent.com/45435906/67120727-2a8c7480-f1ea-11e9-9be9-dc7605be0c30.png)

Lovelace UI:
![image](https://user-images.githubusercontent.com/45435906/67120795-4e4fba80-f1ea-11e9-86a7-d1edb71aaa41.png)

**Home Assistant version**
0.100.2

**Zigbee2mqtt version**
1.6

**OS and browser version**
 Ubuntu 18.04.3LTS,  Chrome 7.0.3865.120 (64 bit)

**Error message on browser**
None

**State attributes of `sensor.zigbee2mqtt_networkmap`**
friendly_name: Zigbee2mqtt Networkmap

**Home Assistant log**
DEBUG (MainThread) [homeassistant.components.mqtt] Subscribing to zigbee2mqtt/bridge/networkmap/raw

**Additional context**
None
