### ISSUE TITLE
names of devices in map

### ISSUE THREAD

**Issue by bartve66** [azuwis/zigbee2mqtt-networkmap#12]
I got this to work, great tool, thanx for the work!
In my map all devices are represented with names like 0x00158d000411b2cf. I edited those type of labels away in home assistant so I can work in scripts etc. with names like sensor. garage_light (and to use the friendly name entry for even more friendly description for the rest of the family).
But it looks like zigbee2mqtt hangs on to names like 0x00158d000411b2cf. How can I get the more friendly names I use in HA in the map?

An additional question: where should I put the 'Full card default options:' in the instruction? I have now put it in a cards segment of the 'raw config editor' of lovelace, but it gets colored red, so i am not very certain I am ding it right?

**Comment by azuwis** [comment]
The names showed in the map are given by Zigbee2mqtt, you can customize them, see https://www.zigbee2mqtt.io/configuration/device_specific_configuration.html for the `friendly_name` option.

In fact if you customize them in this way, HomeAssistant will automatically use the same names when mqtt auto discovery is enabled, which is true in most cases, see https://www.zigbee2mqtt.io/integration/home_assistant.html

Example for card options:
``` yaml
views:
  - title: Zigbee Network
    panel: true # this renders the first card on full width, other cards in this view will not be rendered
    cards:
      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
        mqtt_base_topic: zigbee2mqtt # if you change base_topic of Zigbee2mqtt, change it accordingly
        force: 3000 # decrease it to get smaller map if you have many devices
        node_size: 16
        font_size: 12
        link_width: 2
        height: 400 # height of the card
```
