### ISSUE TITLE
Map isn't working

### ISSUE THREAD

**Issue by AragurDEV** [azuwis/zigbee2mqtt-networkmap#20]
I'm using the latest Version of HomeAssistant, HACSS, and from this Plugin.  
I copied the default config into my ui-lovelace.yaml.  
My network map shows nothing and in my DEV-Console in Chrome, the following error shows:
```
zigbee2mqtt-networkmap.js:7 TypeError: Cannot read property 'attributes' of undefined
    at a.hass (zigbee2mqtt-networkmap.js:7)
    at nr.run (zigbee2mqtt-networkmap.js:7)
    at Kn (zigbee2mqtt-networkmap.js:7)
    at Array.<anonymous> (zigbee2mqtt-networkmap.js:7)
    at ue (zigbee2mqtt-networkmap.js:7)
```

**Comment by azuwis** [comment]
Please fill the issue template, I can not help without detail information.

My setup is HomeAssistant 0.106.6, Zigbee2mqtt 1.11.0, both are latest version, and it works fine.

My best guest is config in `configuration.yaml` is not correct, you need to add sensor even installing using HACS:

```
sensor:
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
```
