### ISSUE TITLE
TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by alexgraupera** [azuwis/zigbee2mqtt-networkmap#24]
Hi!

I have the same error as reported issue: https://github.com/azuwis/zigbee2mqtt-networkmap/issues/20

```
zigbee2mqtt-networkmap.js?v=0.6.0:formatted:802 TypeError: Cannot read property 'attributes' of undefined
	at a.hass (zigbee2mqtt-networkmap.js?v=0.6.0:formatted:4765)
	at nr.run (zigbee2mqtt-networkmap.js?v=0.6.0:formatted:1963)
	at Kn (zigbee2mqtt-networkmap.js?v=0.6.0:formatted:1847)
	at Array.<anonymous> (zigbee2mqtt-networkmap.js?v=0.6.0:formatted:847)
	at ue (zigbee2mqtt-networkmap.js?v=0.6.0:formatted:810)
```

I installed card from HACS (version 1.0.3) and followed this installation steps:

- Installed from HACS UI, and validated that the directory "/www/community/zigbee2mqtt-networkmap" exists and contains zigbee2mqtt-networkmap.js file inside (and js.gz file)
- Added sensor in configuration.yaml (and restarted)
- Added new resource from lovelace control panel with url "/hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js?v=0.6.0". (The installation folder from hacs, 
- Added new custom card with custom type "zigbee2mqtt-networkmap"

When I access to lovelace tab with new card, this show blank result, and console output show the javascript error. I cleaned the cache.

My Setup:

> arch: armv7
> channel: stable
> docker: 19.03.8
> hassos: "4.8"
> homeassistant: 0.110.4
> hostname: hassio
> logging: info
> machine: raspberrypi3
> supervisor: "226"
> supported_arch:
> - armv7
> - armhf

zigbee2mqtt 1.13.1.1
hacs 1.0.3

If you need more information, feel free to request me
Thank you in advance (and sorry for my english)

**Comment by azuwis** [comment]
I've just upgraded zigbee2mqtt to 1.13.1, it works fine.

Make sure `sensor.zigbee2mqtt_networkmap` exists, you can tell by `Developer Tools` -> `STATES`.

If `sensor.zigbee2mqtt_networkmap` does not exist, your configuration is wrong.

``` yaml
sensor:
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
```
