### ISSUE TITLE
Styling big network

### ISSUE THREAD

**Issue by koenhendriks** [azuwis/zigbee2mqtt-networkmap#25]
I recently moved and redid the entire house with Zigbee devices.
![Screenshot 2020-06-10 at 21 58 23](https://user-images.githubusercontent.com/4124579/84312629-89ca3b00-ab65-11ea-8a0b-9ef19f4f409e.png)

My problem now is that I've lost overview in the network map, it has become overpopulated. I tried changing the size but that didn't help with the crowded map.

I was wondering if anyone could help with the structure of the graph to create a better understandable view.

I'm using the following card settings:

```yaml
type: 'custom:zigbee2mqtt-networkmap'
entity: sensor.zigbee2mqtt_networkmap
force: 3000
node_size: 16
font_size: 12
link_width: 2
height: 400
css: |
  :host {
    --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
    --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
    --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
    --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
    --zigbee2mqtt-networkmap-hover-color: #be385d;
    --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
    --zigbee2mqtt-networkmap-label-color: #127862;
    --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
    --zigbee2mqtt-networkmap-node-coordinator-color: rgba(150, 0, 193, .7);
    --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
  }

```

Any tips or help is greatly appreciated.

**Comment by azuwis** [comment]
Try decrease `force`, and use `panel: true`.

```
views:
  - title: Zigbee Network
    panel: true # this renders the first card on full width, other cards in this view will not be rendered
    cards:
      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
        force: 500 # decrease it to get smaller map if you have many devices
```
