### ISSUE TITLE
Update README.md backend setup for current ha release

### ISSUE THREAD

**Issue by pixeldoc2000** [azuwis/zigbee2mqtt-networkmap#38]
Old mqtt config;
```
sensor:
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/response/networkmap
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
    json_attributes_template: "{{ value_json.data.value | tojson }}"
```
New mqtt:
```
mqtt:
  sensor:
    - name: Zigbee2mqtt Networkmap
      # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
      state_topic: zigbee2mqtt/bridge/response/networkmap
      value_template: >-
        {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
      json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      json_attributes_template: "{{ value_json.data.value | tojson }}"
```

**Comment by sultanhq** [comment]
Thank you so much for this :-)  @pixeldoc2000 👍

**Comment by azuwis** [comment]
Close by https://github.com/azuwis/zigbee2mqtt-networkmap/commit/0ddefaf1574fbab57322d26a2f18145d768439e5

**Comment by teras** [comment]
Hello.

I am still struggling to make this to work. To make debugging easier, I was thinking to look at the MQTT broker instead, and **then** search why it's not working with HA.

I was using the proposed template on my `zigbee2mqtt-data/configuration.yaml` file, by having exactly these values alongside existing mqtt: entry, thus the final entry is:
```
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.4:1883
  user: ***
  password: ***
  sensor:
    - name: Zigbee2mqtt Networkmap
      state_topic: zigbee2mqtt/bridge/response/networkmap
      value_template: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
      json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      json_attributes_template: '{{ value_json.data.value | tojson }}'
```

Then I tried to connect directly to MQTT broker, to see what's happening, but there's nothing under `zigbee2mqtt/bridge/response/networkmap` . Of course, `zigbee2mqtt/bridge` exists, but I was expecting to find the rest too.

Am I  missing something?

Thank you!

**Comment by azuwis** [comment]
You can debug the zigbee2mqtt MQTT api using:
```
# run in one console
mosquitto_sub -h 192.168.1.4 -u user -P pass -t 'zigbee2mqtt/bridge/response/networkmap'
# run in another console
mosquitto_pub -h 192.168.1.4 -u user -P pass -t 'zigbee2mqtt/bridge/request/networkmap' -m '{"type": "raw", "routes": true}'
```

Wait about a minute, you should see some JSON data in the mosquitto_sub console.

Did you misunderstand the configuration?  This config:
```
mqtt:
  sensor:
    - name: Zigbee2mqtt Networkmap
      # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
      state_topic: zigbee2mqtt/bridge/response/networkmap
      value_template: >-
        {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
      json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      json_attributes_template: "{{ value_json.data.value | tojson }}"
```

is to be put into `config/configuration.yaml` of Home-Assistant, not Zigbee2mqtt.
