### ISSUE TITLE
Set "routes" to "false" when creating map

### ISSUE THREAD

**Issue by dmatik** [azuwis/zigbee2mqtt-networkmap#45]
When refreshing the map from the card it always uses (includeRoutes 'true').
Can this please be configurable, or at least "false" by default?

**Comment by azuwis** [comment]
Should be fixed by https://github.com/azuwis/zigbee2mqtt-networkmap/commit/ac9661cec21330b1724271439005a105da8c39d4

Please test this js and see if it works [zigbee2mqtt-networkmap.txt](https://github.com/azuwis/zigbee2mqtt-networkmap/files/11483322/zigbee2mqtt-networkmap.txt)

```
    cards:
      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
        mqtt_payload: { type: 'raw', routes: false }
```
