### ISSUE TITLE
stopped working after upgrade to 0.5.0

### ISSUE THREAD

**Issue by MagieMalone** [azuwis/zigbee2mqtt-networkmap#5]
Hassbian OS. Homeassistant version 0.97

upgraded from 0.1.0 to 0.5.0

```
Custom element doesn't exist: zigbee2mqtt-networkmap.
{
  "type": "custom:zigbee2mqtt-networkmap",
  "entity": "sensor.zigbee2mqtt_networkmap"
}
```

and in the log:
``` 
2019-09-03 09:56:00 ERROR (MainThread) [frontend.js.latest.201908050] https://<url>:8123/lovelace/13:0:0 Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".
```

**Comment by azuwis** [comment]
Did `v0.1.0` work?

There should be no changes between `v0.1.0` and `v0.5.0` that cause this kind of problem.

Please check to see if file `<config-directory>/www/zigbee2mqtt-networkmap.js` is broken, md5sum should be `1a5bb83b6e387145679fd86c0332c046`. If not, re download it and retry.

Make sure the version string is changed when retrying.

``` yaml
resources:
  - url: /local/zigbee2mqtt-networkmap.js?v=0.5.0retry # change `v=0.5.0` to `v=0.5.0retry`
    type: module
```
